/* Horizon — 50 marcas, recetas e ingredientes */
(function (global) {
  const ING = {
    pan: { n: "Pan", d: 3, c: 0.25, g: "horno" },
    pan_burger: { n: "Pan de hamburguesa", d: 3, c: 0.28, g: "horno" },
    pan_hotdog: { n: "Pan de perrito", d: 3, c: 0.22, g: "horno" },
    pita: { n: "Pita", d: 3, c: 0.2, g: "horno" },
    tortilla: { n: "Tortilla de maíz", d: 4, c: 0.12, g: "seco" },
    masa: { n: "Masa", d: 2, c: 0.18, g: "horno" },
    arroz: { n: "Arroz", d: 365, c: 0.12, g: "seco" },
    pasta: { n: "Pasta", d: 400, c: 0.2, g: "seco" },
    fideos: { n: "Fideos", d: 200, c: 0.22, g: "seco" },
    noodles: { n: "Noodles", d: 180, c: 0.25, g: "seco" },
    bao: { n: "Masa bao", d: 2, c: 0.2, g: "horno" },
    bagel: { n: "Bagel", d: 3, c: 0.3, g: "horno" },
    croissant: { n: "Cruasán", d: 2, c: 0.4, g: "horno" },
    ternera: { n: "Ternera", d: 3, c: 2.4, g: "carne" },
    wagyu: { n: "Wagyu", d: 3, c: 9.5, g: "carne" },
    cerdo: { n: "Cerdo", d: 3, c: 1.4, g: "carne" },
    pollo: { n: "Pollo", d: 3, c: 1.1, g: "carne" },
    cordero: { n: "Cordero", d: 3, c: 2.2, g: "carne" },
    pavo: { n: "Pavo", d: 3, c: 1.5, g: "carne" },
    bacon: { n: "Bacon", d: 7, c: 1.3, g: "carne" },
    chorizo: { n: "Chorizo", d: 20, c: 1.2, g: "carne" },
    jamon: { n: "Jamón", d: 30, c: 2.8, g: "carne" },
    carne_picada: { n: "Carne picada", d: 2, c: 1.6, g: "carne" },
    costilla: { n: "Costilla", d: 3, c: 2.1, g: "carne" },
    salmon: { n: "Salmón", d: 2, c: 3.4, g: "pescado" },
    atun: { n: "Atún", d: 2, c: 3.8, g: "pescado" },
    bacalao: { n: "Bacalao", d: 3, c: 2.6, g: "pescado" },
    merluza: { n: "Merluza", d: 2, c: 2.2, g: "pescado" },
    gamba: { n: "Gambas", d: 2, c: 3.2, g: "pescado" },
    pulpo: { n: "Pulpo", d: 2, c: 3.0, g: "pescado" },
    calamar: { n: "Calamar", d: 2, c: 1.8, g: "pescado" },
    mejillon: { n: "Mejillones", d: 2, c: 1.4, g: "pescado" },
    vieira: { n: "Vieiras", d: 2, c: 4.2, g: "pescado" },
    anchoa: { n: "Anchoas", d: 40, c: 1.6, g: "pescado" },
    caviar: { n: "Caviar", d: 20, c: 18, g: "pescado" },
    cangrejo: { n: "Cangrejo", d: 2, c: 4.5, g: "pescado" },
    huevo: { n: "Huevos", d: 14, c: 0.22, g: "frio" },
    queso: { n: "Queso", d: 21, c: 1.1, g: "frio" },
    mozzarella: { n: "Mozzarella", d: 10, c: 1.2, g: "frio" },
    parmesano: { n: "Parmesano", d: 60, c: 2.4, g: "frio" },
    cheddar: { n: "Cheddar", d: 30, c: 1.3, g: "frio" },
    feta: { n: "Feta", d: 20, c: 1.4, g: "frio" },
    nata: { n: "Nata", d: 7, c: 0.8, g: "frio" },
    mantequilla: { n: "Mantequilla", d: 30, c: 0.9, g: "frio" },
    leche: { n: "Leche", d: 7, c: 0.18, g: "frio" },
    yogurt: { n: "Yogur", d: 12, c: 0.35, g: "frio" },
    tomate: { n: "Tomate", d: 6, c: 0.25, g: "verde" },
    lechuga: { n: "Lechuga", d: 5, c: 0.2, g: "verde" },
    cebolla: { n: "Cebolla", d: 20, c: 0.12, g: "verde" },
    ajo: { n: "Ajo", d: 40, c: 0.15, g: "verde" },
    pimiento: { n: "Pimiento", d: 8, c: 0.3, g: "verde" },
    chile: { n: "Chile", d: 10, c: 0.2, g: "verde" },
    aguacate: { n: "Aguacate", d: 5, c: 0.9, g: "verde" },
    pepino: { n: "Pepino", d: 7, c: 0.22, g: "verde" },
    lima: { n: "Lima", d: 12, c: 0.3, g: "verde" },
    limon: { n: "Limón", d: 14, c: 0.2, g: "verde" },
    naranja: { n: "Naranja", d: 12, c: 0.25, g: "verde" },
    mango: { n: "Mango", d: 6, c: 0.7, g: "verde" },
    pina: { n: "Piña", d: 7, c: 0.5, g: "verde" },
    coco: { n: "Coco", d: 10, c: 0.6, g: "verde" },
    platano: { n: "Plátano", d: 6, c: 0.3, g: "verde" },
    setas: { n: "Setas", d: 4, c: 0.8, g: "verde" },
    trufa: { n: "Trufa", d: 8, c: 14, g: "verde" },
    patata: { n: "Patata", d: 30, c: 0.15, g: "verde" },
    boniato: { n: "Boniato", d: 20, c: 0.22, g: "verde" },
    maiz: { n: "Maíz", d: 5, c: 0.2, g: "verde" },
    judias: { n: "Judías", d: 4, c: 0.3, g: "verde" },
    garbanzo: { n: "Garbanzos", d: 400, c: 0.18, g: "seco" },
    lenteja: { n: "Lentejas", d: 400, c: 0.16, g: "seco" },
    tofu: { n: "Tofu", d: 10, c: 0.7, g: "frio" },
    algas: { n: "Algas nori", d: 180, c: 0.5, g: "seco" },
    arroz_sushi: { n: "Arroz sushi", d: 365, c: 0.3, g: "seco" },
    wasabi: { n: "Wasabi", d: 90, c: 0.8, g: "seco" },
    soja: { n: "Salsa de soja", d: 400, c: 0.25, g: "seco" },
    miso: { n: "Miso", d: 180, c: 0.5, g: "seco" },
    aceite: { n: "Aceite de oliva", d: 540, c: 0.7, g: "seco" },
    vinagre: { n: "Vinagre", d: 700, c: 0.2, g: "seco" },
    salsa: { n: "Salsa de la casa", d: 14, c: 0.3, g: "frio" },
    ketchup: { n: "Ketchup", d: 180, c: 0.15, g: "seco" },
    mostaza: { n: "Mostaza", d: 180, c: 0.18, g: "seco" },
    mayo: { n: "Mayonesa", d: 30, c: 0.25, g: "frio" },
    curry: { n: "Curry", d: 400, c: 0.4, g: "seco" },
    garam: { n: "Garam masala", d: 400, c: 0.5, g: "seco" },
    comino: { n: "Comino", d: 400, c: 0.3, g: "seco" },
    pimenton: { n: "Pimentón", d: 400, c: 0.25, g: "seco" },
    azafran: { n: "Azafrán", d: 700, c: 6, g: "seco" },
    jengibre: { n: "Jengibre", d: 14, c: 0.35, g: "verde" },
    cilantro: { n: "Cilantro", d: 4, c: 0.2, g: "verde" },
    albahaca: { n: "Albahaca", d: 5, c: 0.3, g: "verde" },
    menta: { n: "Menta", d: 5, c: 0.25, g: "verde" },
    romero: { n: "Romero", d: 10, c: 0.2, g: "verde" },
    ajonjoli: { n: "Sésamo", d: 300, c: 0.4, g: "seco" },
    cacahuete: { n: "Cacahuete", d: 180, c: 0.35, g: "seco" },
    almendra: { n: "Almendras", d: 180, c: 0.8, g: "seco" },
    chocolate: { n: "Chocolate", d: 180, c: 0.9, g: "seco" },
    azucar: { n: "Azúcar", d: 700, c: 0.1, g: "seco" },
    miel: { n: "Miel", d: 700, c: 0.6, g: "seco" },
    cafe: { n: "Café", d: 180, c: 0.7, g: "seco" },
    te: { n: "Té", d: 365, c: 0.4, g: "seco" },
    hielo: { n: "Hielo", d: 1, c: 0.02, g: "frio" },
    soda: { n: "Soda", d: 180, c: 0.15, g: "seco" },
    cerveza: { n: "Cerveza", d: 90, c: 0.7, g: "bar", alc: true },
    vino_tinto: { n: "Vino tinto", d: 700, c: 1.4, g: "bar", alc: true },
    vino_blanco: { n: "Vino blanco", d: 400, c: 1.3, g: "bar", alc: true },
    cava: { n: "Cava / champán", d: 700, c: 3.5, g: "bar", alc: true },
    whisky: { n: "Whisky", d: 2000, c: 2.8, g: "bar", alc: true },
    ron: { n: "Ron", d: 2000, c: 1.8, g: "bar", alc: true },
    vodka: { n: "Vodka", d: 2000, c: 1.6, g: "bar", alc: true },
    ginebra: { n: "Ginebra", d: 2000, c: 1.9, g: "bar", alc: true },
    tequila: { n: "Tequila", d: 2000, c: 2.2, g: "bar", alc: true },
    mezcal: { n: "Mezcal", d: 2000, c: 2.6, g: "bar", alc: true },
    vermut: { n: "Vermú", d: 400, c: 1.2, g: "bar", alc: true },
    absenta: { n: "Absenta", d: 2000, c: 3.2, g: "bar", alc: true },
    licor: { n: "Licor", d: 1000, c: 1.5, g: "bar", alc: true },
    brandy: { n: "Brandy", d: 2000, c: 2.4, g: "bar", alc: true },
    agua: { n: "Agua", d: 700, c: 0.05, g: "seco" },
    caldo: { n: "Caldo", d: 4, c: 0.3, g: "frio" },
    kimchi: { n: "Kimchi", d: 30, c: 0.5, g: "frio" },
    algas_wakame: { n: "Wakame", d: 180, c: 0.45, g: "seco" },
    edamame: { n: "Edamame", d: 7, c: 0.5, g: "frio" },
    quinoa: { n: "Quinoa", d: 365, c: 0.6, g: "seco" },
    platano_macho: { n: "Plátano macho", d: 7, c: 0.25, g: "verde" },
    yuca: { n: "Yuca", d: 10, c: 0.2, g: "verde" },
    jerk: { n: "Especias jerk", d: 400, c: 0.45, g: "seco" },
    harissa: { n: "Harissa", d: 90, c: 0.4, g: "seco" },
    tahini: { n: "Tahini", d: 180, c: 0.55, g: "seco" },
    hummus: { n: "Hummus", d: 5, c: 0.4, g: "frio" },
    tzatziki: { n: "Tzatziki", d: 5, c: 0.4, g: "frio" },
    dukkah: { n: "Dukkah", d: 120, c: 0.5, g: "seco" },
    masa_empanada: { n: "Masa empanada", d: 3, c: 0.2, g: "horno" },
    masa_pierogi: { n: "Masa pierogi", d: 3, c: 0.2, g: "horno" },
    queso_raclette: { n: "Raclette", d: 20, c: 2.0, g: "frio" },
    queso_gruyere: { n: "Gruyère", d: 40, c: 2.2, g: "frio" },
    chocolate_cacao: { n: "Cacao", d: 365, c: 1.1, g: "seco" },
    vainilla: { n: "Vainilla", d: 700, c: 1.4, g: "seco" },
    canela: { n: "Canela", d: 700, c: 0.4, g: "seco" },
    cardamomo: { n: "Cardamomo", d: 400, c: 0.8, g: "seco" },
    clavo: { n: "Clavo", d: 700, c: 0.5, g: "seco" },
    anis: { n: "Anís", d: 700, c: 0.4, g: "seco" },
    merengue: { n: "Merengue", d: 3, c: 0.4, g: "horno" },
    foie: { n: "Foie", d: 5, c: 8, g: "carne" },
    langosta: { n: "Langosta", d: 2, c: 12, g: "pescado" },
    ostra: { n: "Ostras", d: 2, c: 4, g: "pescado" },
    trufa_blanca: { n: "Trufa blanca", d: 5, c: 22, g: "verde" },
    kobe: { n: "Kobe", d: 3, c: 16, g: "carne" },
    ibérico: { n: "Ibérico", d: 20, c: 6, g: "carne" },
    percebe: { n: "Percebes", d: 2, c: 7, g: "pescado" },
    aceituna: { n: "Aceitunas", d: 90, c: 0.5, g: "seco" },
    manzana: { n: "Manzana", d: 20, c: 0.25, g: "verde" },
    berenjena: { n: "Berenjena", d: 7, c: 0.3, g: "verde" },
    espinaca: { n: "Espinaca", d: 4, c: 0.25, g: "verde" },
    sake: { n: "Sake", d: 400, c: 1.8, g: "bar", alc: true },
    pato: { n: "Pato", d: 3, c: 2.6, g: "carne" },
    datil: { n: "Dátiles", d: 120, c: 0.5, g: "seco" },
    oregano: { n: "Orégano", d: 400, c: 0.2, g: "seco" },
    perejil: { n: "Perejil", d: 5, c: 0.15, g: "verde" },
    pepinillo: { n: "Pepinillo", d: 180, c: 0.25, g: "seco" },
    remolacha: { n: "Remolacha", d: 14, c: 0.22, g: "verde" },
    avena: { n: "Avena", d: 365, c: 0.18, g: "seco" },
    calabaza: { n: "Calabaza", d: 20, c: 0.22, g: "verde" },
    fruta: { n: "Fruta", d: 5, c: 0.4, g: "verde" },
    galleta: { n: "Galleta", d: 40, c: 0.3, g: "seco" },
    mermelada: { n: "Mermelada", d: 180, c: 0.35, g: "seco" },
    repollo: { n: "Repollo", d: 12, c: 0.18, g: "verde" },
    ricotta: { n: "Ricotta", d: 10, c: 0.9, g: "frio" },
    verdura: { n: "Verdura", d: 5, c: 0.25, g: "verde" },
    sal: { n: "Sal", d: 2000, c: 0.02, g: "seco" },
    yema: { n: "Yema", d: 10, c: 0.2, g: "frio" },
    zanahoria: { n: "Zanahoria", d: 20, c: 0.18, g: "verde" },
    hierbas: { n: "Hierbas", d: 8, c: 0.3, g: "verde" },
    hinojo: { n: "Hinojo", d: 8, c: 0.35, g: "verde" },
    avellana: { n: "Avellana", d: 180, c: 0.7, g: "seco" },
  };

  const TIERS = {
    food_truck: { id: "food_truck", name: "Food truck", ticket: 0.72, hours: [11, 23], staffBias: { cocinero: 1, camarero: 0.4 } },
    fast_food: { id: "fast_food", name: "Comida rápida", ticket: 0.8, hours: [10, 24], staffBias: { cocinero: 1, camarero: 0.8 } },
    casual: { id: "casual", name: "Casual", ticket: 1, hours: [12, 23], staffBias: { cocinero: 1, camarero: 1, gerente: 1 } },
    luxury: { id: "luxury", name: "Lujo", ticket: 2.4, hours: [13, 16, 19, 23], staffBias: { cocinero: 1.4, camarero: 1.2, gerente: 1.3 } },
    bar: { id: "bar", name: "Bar", ticket: 1.15, hours: [17, 27], staffBias: { bartender: 1.4, camarero: 1, gerente: 0.8 } },
  };

  function D(name, ings, cost, price, flags = "") {
    return {
      name,
      ings,
      cost,
      price,
      veg: flags.includes("v"),
      alc: flags.includes("a"),
      spicy: flags.includes("s"),
      sig: flags.includes("*"),
    };
  }

  function logoSVG(b, size = 64) {
    const rng = U.mulberry32(U.hash32(b.id + b.name));
    const shapes = [];
    const n = 2 + ((rng() * 3) | 0);
    for (let i = 0; i < n; i++) {
      const t = rng();
      const x = 8 + rng() * 48;
      const y = 8 + rng() * 48;
      const s = 10 + rng() * 28;
      const op = (0.18 + rng() * 0.35).toFixed(2);
      const fill = i % 2 ? b.color2 : "#fff";
      if (t < 0.33) shapes.push(`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${(s / 2).toFixed(1)}" fill="${fill}" opacity="${op}"/>`);
      else if (t < 0.66)
        shapes.push(
          `<rect x="${(x - s / 2).toFixed(1)}" y="${(y - s / 2).toFixed(1)}" width="${s.toFixed(1)}" height="${s.toFixed(1)}" rx="${(4 + rng() * 10).toFixed(1)}" fill="${fill}" opacity="${op}"/>`
        );
      else
        shapes.push(
          `<polygon points="${x.toFixed(1)},${(y - s / 2).toFixed(1)} ${(x + s / 2).toFixed(1)},${(y + s / 2).toFixed(1)} ${(x - s / 2).toFixed(1)},${(y + s / 2).toFixed(1)}" fill="${fill}" opacity="${op}"/>`
        );
    }
    const font = Math.round(size * (b.short.length > 2 ? 0.28 : 0.34));
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 64 64">
      <defs><linearGradient id="g${b.id}" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="${b.color}"/><stop offset="1" stop-color="${b.color2}"/>
      </linearGradient></defs>
      <rect width="64" height="64" rx="16" fill="url(#g${b.id})"/>
      ${shapes.join("")}
      <text x="32" y="38" text-anchor="middle" font-family="Georgia, serif" font-size="${font}" font-weight="700" fill="#fff">${b.short}</text>
    </svg>`;
  }

  const BRANDS = [
    {
      id: "bufalo",
      name: "Sabor Burger",
      short: "BR",
      cuisines: ["americana", "hamburguesas"],
      tier: "fast_food",
      color: "#E85D04",
      color2: "#9B2226",
      tagline: "La tormenta en un pan.",
      dishes: [
        D("Relámpago clásica", ["pan_burger", "carne_picada", "cheddar", "lechuga", "tomate", "salsa"], 1.6, 5.9, "*"),
        D("Doble búfalo", ["pan_burger", "carne_picada", "bacon", "cheddar", "salsa"], 2.4, 7.9, "s"),
        D("Pollo crujiente", ["pan_burger", "pollo", "lechuga", "mayo"], 1.5, 5.5, ""),
        D("Vegetal del prado", ["pan_burger", "tofu", "lechuga", "tomate", "salsa"], 1.3, 5.2, "v"),
        D("Patatas rayo", ["patata", "aceite", "pimenton"], 0.4, 2.4, "v"),
        D("Batido eclipse", ["leche", "chocolate", "azucar"], 0.6, 3.2, "v"),
        D("Aros de cebolla", ["cebolla", "masa", "aceite"], 0.5, 2.8, "v"),
        D("Kids búfalo", ["pan_burger", "carne_picada", "ketchup"], 1.0, 3.9, ""),
      ],
    },
    {
      id: "pollo",
      name: "Rama Pollo",
      short: "PR",
      cuisines: ["americana", "pollo frito"],
      tier: "fast_food",
      color: "#F4A261",
      color2: "#E76F51",
      tagline: "Crujiente como un trueno.",
      dishes: [
        D("Cubo rayo 6", ["pollo", "aceite", "pimenton"], 2.1, 7.5, "*"),
        D("Alitas infierno", ["pollo", "chile", "salsa"], 1.8, 6.9, "s"),
        D("Sándwich tormenta", ["pan", "pollo", "mayo", "lechuga"], 1.4, 5.4, ""),
        D("Tenders", ["pollo", "aceite"], 1.5, 5.8, ""),
        D("Mazorca mantequilla", ["maiz", "mantequilla"], 0.5, 2.5, "v"),
        D("Coleslaw", ["lechuga", "mayo"], 0.4, 2.2, "v"),
        D("Refresco casa", ["soda", "hielo", "limon"], 0.2, 1.8, "v"),
        D("Tarta chocolate", ["chocolate", "huevo", "azucar"], 0.7, 3.4, "v"),
      ],
    },
    {
      id: "taco",
      name: "Sabo Tacos",
      short: "TR",
      cuisines: ["mexicana", "tex-mex"],
      tier: "fast_food",
      color: "#E9C46A",
      color2: "#E76F51",
      tagline: "La hora exacta del taco.",
      dishes: [
        D("Taco al pastor", ["tortilla", "cerdo", "pina", "cilantro", "cebolla"], 1.2, 3.8, "*s"),
        D("Taco de asada", ["tortilla", "ternera", "cilantro", "cebolla", "lima"], 1.4, 4.2, ""),
        D("Taco pescado", ["tortilla", "bacalao", "repollo".replace("repollo","lechuga"), "lima", "salsa"], 1.3, 4.4, ""),
        D("Quesadilla", ["tortilla", "queso", "pimiento"], 1.0, 4.0, "v"),
        D("Nachos brújula", ["maiz", "queso", "chile", "aguacate"], 1.1, 4.8, "v"),
        D("Guacamole y totopos", ["aguacate", "lima", "tomate", "maiz"], 0.9, 3.9, "v"),
        D("Horchata", ["leche", "canela", "azucar"], 0.4, 2.2, "v"),
        D("Churro reloj", ["masa", "azucar", "canela"], 0.4, 2.5, "v"),
      ],
    },
    {
      id: "pizza",
      name: "Orama Pizza",
      short: "PK",
      cuisines: ["italiana", "pizza"],
      tier: "fast_food",
      color: "#D62828",
      color2: "#2A9D8F",
      tagline: "Un kilómetro de masa, una bocado de casa.",
      dishes: [
        D("Margarita km 0", ["masa", "tomate", "mozzarella", "albahaca"], 1.2, 7.5, "v*"),
        D("Diávola", ["masa", "tomate", "mozzarella", "chorizo", "chile"], 1.6, 8.9, "s"),
        D("Cuatro estaciones", ["masa", "tomate", "mozzarella", "setas", "jamon"], 1.7, 9.2, ""),
        D("Quattro formaggi", ["masa", "mozzarella", "queso", "parmesano", "cheddar"], 1.8, 9.5, "v"),
        D("Marinara", ["masa", "tomate", "ajo", "aceite"], 0.9, 6.5, "v"),
        D("Calzone", ["masa", "ricotta".replace("ricotta","queso"), "jamon", "mozzarella"], 1.6, 8.8, ""),
        D("Focaccia", ["masa", "aceite", "romero"], 0.6, 3.5, "v"),
        D("Tiramisú vaso", ["cafe", "queso", "azucar", "cacao".replace("cacao","chocolate")], 0.8, 4.2, "v"),
      ],
    },
    {
      id: "doner",
      name: "Sabor Döner",
      short: "DB",
      cuisines: ["turca", "kebab"],
      tier: "fast_food",
      color: "#6A994E",
      color2: "#386641",
      tagline: "El norte siempre apunta al espeto.",
      dishes: [
        D("Döner clásico", ["pita", "ternera", "lechuga", "tomate", "salsa"], 1.5, 5.5, "*"),
        D("Döner pollo", ["pita", "pollo", "lechuga", "salsa"], 1.3, 5.2, ""),
        D("Dürüm", ["tortilla", "ternera", "cebolla", "salsa"], 1.6, 5.9, ""),
        D("Lahmacun", ["masa", "carne_picada", "tomate", "pimiento"], 1.2, 4.8, ""),
        D("Falafel brújula", ["garbanzo", "pita", "tahini", "lechuga"], 1.0, 4.9, "v"),
        D("Patatas sazonadas", ["patata", "pimenton", "aceite"], 0.4, 2.4, "v"),
        D("Ayran", ["yogurt", "agua", "sal".replace("sal","comino")], 0.3, 1.8, "v"),
        D("Baklava", ["almendra", "miel", "mantequilla"], 0.7, 3.2, "v"),
      ],
    },
    {
      id: "bao",
      name: "Rama Bao",
      short: "BM",
      cuisines: ["china", "bao"],
      tier: "food_truck",
      color: "#BC4749",
      color2: "#6D2E46",
      tagline: "Pequeño al vapor, enorme en sabor.",
      dishes: [
        D("Bao cerdo char siu", ["bao", "cerdo", "soja", "azucar"], 1.1, 3.6, "*"),
        D("Bao pollo jengibre", ["bao", "pollo", "jengibre", "soja"], 1.0, 3.5, ""),
        D("Bao shiitake", ["bao", "setas", "soja", "ajonjoli"], 0.9, 3.4, "v"),
        D("Bao pato", ["bao", "pavo", "soja", "pepino"], 1.3, 4.2, ""),
        D("Edamame sal", ["edamame"], 0.5, 2.4, "v"),
        D("Sopa wonton vaso", ["fideos", "cerdo", "caldo", "soja"], 0.9, 3.8, ""),
        D("Té jazmín", ["te"], 0.2, 1.6, "v"),
        D("Bollo loto", ["bao", "azucar"], 0.5, 2.2, "v"),
      ],
    },
    {
      id: "falafel",
      name: "Sabo Falafel",
      short: "FN",
      cuisines: ["levantina", "callejera"],
      tier: "food_truck",
      color: "#588157",
      color2: "#3A5A40",
      tagline: "El norte sabe a comino y sésamo.",
      dishes: [
        D("Falafel pita", ["garbanzo", "pita", "tahini", "lechuga", "tomate"], 1.0, 4.5, "v*"),
        D("Shawarma norte", ["pita", "pollo", "tahini", "pepino"], 1.3, 5.4, ""),
        D("Hummus plato", ["hummus", "aceite", "pita"], 0.8, 3.9, "v"),
        D("Tabulé", ["tomate", "pepino", "menta", "limon"], 0.7, 3.8, "v"),
        D("Patatas harissa", ["patata", "harissa", "aceite"], 0.5, 2.8, "vs"),
        D("Limonada menta", ["limon", "menta", "azucar", "hielo"], 0.3, 2.2, "v"),
        D("Baklava pistacho", ["almendra", "miel"], 0.7, 3.0, "v"),
        D("Agua de azahar", ["agua", "azucar", "naranja"], 0.2, 1.8, "v"),
      ],
    },
    {
      id: "frankfurt",
      name: "Orama Frankfurt",
      short: "FP",
      cuisines: ["alemana", "hot dog"],
      tier: "food_truck",
      color: "#9B2226",
      color2: "#BB3E03",
      tagline: "Un perrito para el invierno y el verano.",
      dishes: [
        D("Polar clásico", ["pan_hotdog", "cerdo", "mostaza", "ketchup"], 1.0, 3.9, "*"),
        D("Chili dog", ["pan_hotdog", "cerdo", "carne_picada", "chile", "cheddar"], 1.5, 5.2, "s"),
        D("Dog kimchi", ["pan_hotdog", "cerdo", "kimchi", "mayo"], 1.3, 4.8, "s"),
        D("Veggie dog", ["pan_hotdog", "tofu", "mostaza"], 0.9, 3.8, "v"),
        D("Bretzel", ["masa", "mostaza"], 0.5, 2.6, "v"),
        D("Choucroute vaso", ["lechuga", "vinagre", "cerdo"], 0.7, 3.2, ""),
        D("Cerveza polar", ["cerveza", "hielo"], 0.7, 3.5, "a"),
        D("Apfelschorle", ["naranja", "soda"], 0.4, 2.4, "v"),
      ],
    },
    {
      id: "empanada",
      name: "Sabor Empanada",
      short: "ES",
      cuisines: ["argentina", "empanadas"],
      tier: "food_truck",
      color: "#C1121F",
      color2: "#780000",
      tagline: "El sur se dobla y se hornea.",
      dishes: [
        D("Carne suave", ["masa_empanada", "carne_picada", "cebolla", "huevo"], 1.1, 2.8, "*"),
        D("Carne picante", ["masa_empanada", "carne_picada", "chile", "comino"], 1.1, 2.8, "s"),
        D("Humita", ["masa_empanada", "maiz", "queso"], 0.9, 2.6, "v"),
        D("Queso y cebolla", ["masa_empanada", "queso", "cebolla"], 0.9, 2.6, "v"),
        D("Atún", ["masa_empanada", "atun", "huevo", "cebolla"], 1.2, 3.0, ""),
        D("Jamón y queso", ["masa_empanada", "jamon", "queso"], 1.1, 2.9, ""),
        D("Chimichurri", ["perejil".replace("perejil","cilantro"), "ajo", "aceite", "vinagre"], 0.3, 0.8, "v"),
        D("Dulce de leche", ["masa_empanada", "leche", "azucar"], 0.7, 2.4, "v"),
      ],
    },
    {
      id: "cinta",
      name: "Rama Sushi",
      short: "SC",
      cuisines: ["japonesa", "sushi"],
      tier: "fast_food",
      color: "#1D3557",
      color2: "#E63946",
      tagline: "La cinta no para. Tú tampoco.",
      dishes: [
        D("Nigiri salmón", ["arroz_sushi", "salmon", "wasabi"], 1.4, 3.2, "*"),
        D("Nigiri atún", ["arroz_sushi", "atun", "wasabi"], 1.6, 3.6, ""),
        D("Maki pepino", ["arroz_sushi", "algas", "pepino"], 0.7, 2.4, "v"),
        D("California", ["arroz_sushi", "algas", "cangrejo", "aguacate"], 1.3, 3.8, ""),
        D("Sashimi mix", ["salmon", "atun"], 2.4, 8.5, ""),
        D("Edamame", ["edamame"], 0.5, 2.5, "v"),
        D("Miso taza", ["miso", "tofu", "algas_wakame"], 0.6, 2.8, "v"),
        D("Té verde", ["te"], 0.2, 1.5, "v"),
      ],
    },
    {
      id: "vesubio",
      name: "Sabora Pasta",
      short: "TV",
      cuisines: ["italiana"],
      tier: "casual",
      color: "#2A9D8F",
      color2: "#264653",
      tagline: "La lava es de tomate y albahaca.",
      dishes: [
        D("Spaghetti pomodoro", ["pasta", "tomate", "albahaca", "aceite"], 1.4, 9.5, "v*"),
        D("Tagliatelle ragú", ["pasta", "carne_picada", "tomate", "parmesano"], 2.2, 12.5, ""),
        D("Risotto setas", ["arroz", "setas", "parmesano", "mantequilla"], 2.0, 13.0, "v"),
        D("Ossobuco", ["ternera", "vino_tinto", "romero"], 4.2, 18.5, ""),
        D("Insalata caprese", ["tomate", "mozzarella", "albahaca", "aceite"], 1.6, 8.5, "v"),
        D("Tiramisú", ["cafe", "queso", "azucar", "huevo"], 1.1, 6.0, "v"),
        D("Vino de la casa", ["vino_tinto"], 1.4, 5.5, "a"),
        D("Espresso", ["cafe"], 0.3, 1.8, "v"),
      ],
    },
    {
      id: "olivo",
      name: "Sabor Tapas",
      short: "TO",
      cuisines: ["española", "tapas"],
      tier: "casual",
      color: "#606C38",
      color2: "#283618",
      tagline: "Aceite, barra y conversación.",
      dishes: [
        D("Tortilla de patatas", ["huevo", "patata", "cebolla", "aceite"], 1.2, 6.5, "v*"),
        D("Jamón y pan tomate", ["jamon", "pan", "tomate", "aceite"], 2.4, 9.5, ""),
        D("Pulpo a feria", ["pulpo", "pimenton", "patata", "aceite"], 3.0, 14.0, ""),
        D("Gambas al ajillo", ["gamba", "ajo", "chile", "aceite"], 2.6, 12.5, "s"),
        D("Croquetas", ["leche", "jamon", "mantequilla"], 1.1, 6.0, ""),
        D("Ensaladilla", ["patata", "mayo", "huevo", "atun"], 1.0, 5.5, ""),
        D("Caña", ["cerveza"], 0.7, 2.8, "a"),
        D("Churros con chocolate", ["masa", "chocolate", "azucar"], 0.8, 4.5, "v"),
      ],
    },
    {
      id: "linterna",
      name: "Rama Bistró",
      short: "BL",
      cuisines: ["francesa"],
      tier: "casual",
      color: "#3D405B",
      color2: "#E07A5F",
      tagline: "La linterna se enciende a mediodía.",
      dishes: [
        D("Steak frites", ["ternera", "patata", "mantequilla"], 3.8, 16.5, "*"),
        D("Croque monsieur", ["pan", "jamon", "queso", "mantequilla"], 1.6, 8.5, ""),
        D("Sopa cebolla", ["cebolla", "caldo", "queso", "pan"], 1.2, 7.5, "v"),
        D("Quiche Lorraine", ["huevo", "nata", "bacon", "masa"], 1.5, 8.0, ""),
        D("Salade niçoise", ["atun", "huevo", "tomate", "anchoa"], 2.2, 11.0, ""),
        D("Crème brûlée", ["nata", "huevo", "azucar", "vainilla"], 1.0, 5.8, "v"),
        D("Copa de tinto", ["vino_tinto"], 1.4, 5.0, "a"),
        D("Café crème", ["cafe", "leche"], 0.4, 2.2, "v"),
      ],
    },
    {
      id: "monzon",
      name: "Sabo Curry",
      short: "CM",
      cuisines: ["india"],
      tier: "casual",
      color: "#DC2F02",
      color2: "#F48C06",
      tagline: "Cuando llega el monzón, huele a garam.",
      dishes: [
        D("Chicken tikka masala", ["pollo", "yogurt", "tomate", "garam", "nata"], 2.2, 11.5, "*"),
        D("Lamb rogan josh", ["cordero", "garam", "tomate", "chile"], 2.8, 13.5, "s"),
        D("Palak paneer", ["queso", "judias", "garam"], 1.6, 10.0, "v"),
        D("Dal tadka", ["lenteja", "ajo", "comino"], 0.9, 7.5, "v"),
        D("Biryani", ["arroz", "pollo", "cardamomo", "azafran"], 2.0, 12.0, ""),
        D("Naan ajo", ["masa", "ajo", "mantequilla"], 0.5, 2.8, "v"),
        D("Samosa", ["masa", "patata", "judias", "comino"], 0.6, 3.5, "v"),
        D("Lassi mango", ["yogurt", "mango", "azucar"], 0.6, 3.2, "v"),
      ],
    },
    {
      id: "wok",
      name: "Orama Wok",
      short: "WD",
      cuisines: ["china"],
      tier: "casual",
      color: "#9B2226",
      color2: "#CA6702",
      tagline: "El dragón salta en el wok.",
      dishes: [
        D("Pollo kung pao", ["pollo", "cacahuete", "chile", "soja"], 1.8, 10.5, "*s"),
        D("Ternera con brócoli", ["ternera", "soja", "ajo"], 2.2, 11.5, ""),
        D("Ma po tofu", ["tofu", "cerdo", "chile", "soja"], 1.4, 9.5, "s"),
        D("Arroz frito", ["arroz", "huevo", "cebolla", "soja"], 1.1, 7.5, ""),
        D("Rollitos primavera", ["masa", "verdura".replace("verdura","lechuga"), "aceite"], 0.8, 4.5, "v"),
        D("Pato pekín (ración)", ["pavo", "pepino", "salsa", "tortilla"], 3.4, 16.0, ""),
        D("Sopa agripicante", ["caldo", "tofu", "chile", "vinagre"], 0.9, 5.5, "s"),
        D("Té oolong", ["te"], 0.2, 1.8, "v"),
      ],
    },
    {
      id: "seul",
      name: "Sabor Seúl",
      short: "SP",
      cuisines: ["coreana"],
      tier: "casual",
      color: "#D00000",
      color2: "#212529",
      tagline: "La parrilla de Seúl, a cualquier latitud.",
      dishes: [
        D("Bulgogi", ["ternera", "soja", "ajonjoli", "ajo"], 2.6, 14.0, "*"),
        D("Samgyeopsal", ["cerdo", "lechuga", "ajo"], 2.2, 13.0, ""),
        D("Bibimbap", ["arroz", "huevo", "setas", "kimchi"], 1.8, 11.0, ""),
        D("Kimchi jjigae", ["kimchi", "cerdo", "tofu", "caldo"], 1.6, 10.5, "s"),
        D("Tteokbokki", ["masa", "chile", "soja"], 1.1, 7.5, "vs"),
        D("Banchan surtido", ["kimchi", "judias", "ajonjoli"], 0.8, 4.5, "v"),
        D("Soju copa", ["licor"], 1.5, 4.5, "a"),
        D("Sikhye", ["arroz", "azucar", "agua"], 0.3, 2.2, "v"),
      ],
    },
    {
      id: "thai",
      name: "Rama Thai",
      short: "TM",
      cuisines: ["tailandesa"],
      tier: "casual",
      color: "#80B918",
      color2: "#2B9348",
      tagline: "Dulce, ácido, picante, mango.",
      dishes: [
        D("Pad thai", ["noodles", "gamba", "cacahuete", "lima", "huevo"], 2.0, 11.5, "*"),
        D("Green curry", ["pollo", "leche", "chile", "albahaca"], 2.1, 12.0, "s"),
        D("Tom yum", ["caldo", "gamba", "lima", "chile", "setas"], 1.8, 9.5, "s"),
        D("Mango sticky rice", ["arroz", "mango", "coco", "azucar"], 1.0, 5.5, "v"),
        D("Som tam", ["papaya".replace("papaya","mango"), "lima", "chile", "cacahuete"], 0.9, 7.5, "vs"),
        D("Satay pollo", ["pollo", "cacahuete", "soja"], 1.5, 8.5, ""),
        D("Arroz jazmín", ["arroz"], 0.3, 2.5, "v"),
        D("Thai iced tea", ["te", "leche", "azucar", "hielo"], 0.4, 2.8, "v"),
      ],
    },
    {
      id: "nudo",
      name: "Sabo Ramen",
      short: "RN",
      cuisines: ["japonesa", "ramen"],
      tier: "casual",
      color: "#7F4F24",
      color2: "#C9A227",
      tagline: "El nudo se deshace en el caldo.",
      dishes: [
        D("Tonkotsu", ["fideos", "cerdo", "caldo", "huevo", "ajonjoli"], 2.2, 11.5, "*"),
        D("Shoyu", ["fideos", "pollo", "soja", "caldo", "huevo"], 1.9, 10.5, ""),
        D("Miso ramen", ["fideos", "miso", "cerdo", "maiz", "mantequilla"], 2.0, 11.0, ""),
        D("Veggie ramen", ["fideos", "miso", "tofu", "setas", "algas_wakame"], 1.6, 9.8, "v"),
        D("Gyoza", ["masa", "cerdo", "ajo", "soja"], 1.1, 5.5, ""),
        D("Chashu extra", ["cerdo", "soja"], 1.2, 3.5, ""),
        D("Cerveza japonica", ["cerveza"], 0.7, 3.8, "a"),
        D("Ramune", ["soda", "limon"], 0.3, 2.4, "v"),
      ],
    },
    {
      id: "mezze",
      name: "Orama Mezze",
      short: "ML",
      cuisines: ["libanesa", "mediterránea"],
      tier: "casual",
      color: "#90A955",
      color2: "#4F772D",
      tagline: "Pequeños platos, luna llena.",
      dishes: [
        D("Mezze luna", ["hummus", "tahini", "pita", "pepino", "tomate"], 1.8, 12.0, "v*"),
        D("Kafta", ["cordero", "comino", "perejil".replace("perejil","cilantro"), "cebolla"], 2.4, 13.5, ""),
        D("Fattoush", ["tomate", "pepino", "pita", "limon", "menta"], 1.2, 8.0, "v"),
        D("Kibbeh", ["cordero", "trigo".replace("trigo","masa"), "comino"], 2.0, 11.0, ""),
        D("Labneh miel", ["yogurt", "miel", "aceite"], 0.8, 5.5, "v"),
        D("Falafel", ["garbanzo", "comino", "aceite"], 0.8, 6.0, "v"),
        D("Arak", ["licor", "hielo", "agua"], 1.6, 5.5, "a"),
        D("Café de cardamomo", ["cafe", "cardamomo"], 0.4, 2.2, "v"),
      ],
    },
    {
      id: "gyros",
      name: "Sabor Gyros",
      short: "GM",
      cuisines: ["griega"],
      tier: "casual",
      color: "#277DA1",
      color2: "#4D908E",
      tagline: "Mármol blanco, carne girando.",
      dishes: [
        D("Gyros plato", ["pita", "cerdo", "tzatziki", "tomate", "cebolla"], 1.8, 10.5, "*"),
        D("Souvlaki pollo", ["pollo", "limon", "aceite", "pita"], 1.7, 10.0, ""),
        D("Moussaka", ["ternera", "patata", "berenjena".replace("berenjena","tomate"), "nata"], 2.2, 12.5, ""),
        D("Horiatiki", ["tomate", "pepino", "feta", "aceite"], 1.5, 8.5, "v"),
        D("Calamares", ["calamar", "limon", "aceite"], 1.8, 9.5, ""),
        D("Saganaki", ["queso", "limon"], 1.2, 7.0, "v"),
        D("Ouzo", ["licor", "hielo"], 1.5, 4.5, "a"),
        D("Yogur miel nuez", ["yogurt", "miel", "almendra"], 0.8, 4.8, "v"),
      ],
    },
    {
      id: "pho",
      name: "Rama Phở",
      short: "PH",
      cuisines: ["vietnamita"],
      tier: "casual",
      color: "#2D6A4F",
      color2: "#95D5B2",
      tagline: "El río largo es un caldo.",
      dishes: [
        D("Phở bò", ["fideos", "ternera", "caldo", "lima", "cilantro"], 1.8, 10.5, "*"),
        D("Phở gà", ["fideos", "pollo", "caldo", "lima"], 1.6, 9.8, ""),
        D("Bánh mì", ["pan", "cerdo", "cilantro", "pepino", "chile"], 1.3, 6.5, "s"),
        D("Gỏi cuốn", ["gamba", "fideos", "menta", "lima"], 1.4, 7.0, ""),
        D("Bún chả", ["fideos", "cerdo", "lima", "salsa"], 1.7, 10.0, ""),
        D("Cà phê sữa", ["cafe", "leche", "azucar", "hielo"], 0.5, 2.8, "v"),
        D("Primavera frita", ["masa", "cerdo", "aceite"], 0.9, 4.5, ""),
        D("Agua de coco", ["coco", "hielo"], 0.5, 2.6, "v"),
      ],
    },
    {
      id: "pampa",
      name: "Sabo Churrasco",
      short: "CP",
      cuisines: ["brasileña", "parrilla"],
      tier: "casual",
      color: "#007F5F",
      color2: "#2B9348",
      tagline: "La pampa cabe en una espada.",
      dishes: [
        D("Picanha", ["ternera", "sal".replace("sal","pimenton"), "aceite"], 4.0, 18.0, "*"),
        D("Linguiça", ["cerdo", "comino"], 1.8, 9.5, ""),
        D("Pollo corazón", ["pollo", "limon"], 1.6, 9.0, ""),
        D("Feijoada", ["judias", "cerdo", "arroz"], 1.8, 11.0, ""),
        D("Farofa y vinagrete", ["maiz", "tomate", "cebolla", "vinagre"], 0.6, 3.5, "v"),
        D("Pão de queijo", ["queso", "masa"], 0.6, 3.8, "v"),
        D("Caipirinha", ["licor", "lima", "azucar", "hielo"], 1.4, 6.5, "a"),
        D("Brigadeiro", ["chocolate", "leche", "azucar"], 0.5, 3.2, "v"),
      ],
    },
    {
      id: "ola",
      name: "Orama Ceviche",
      short: "CO",
      cuisines: ["peruana"],
      tier: "casual",
      color: "#00B4D8",
      color2: "#0077B6",
      tagline: "La ola cura el pescado.",
      dishes: [
        D("Ceviche clásico", ["merluza", "lima", "chile", "cebolla", "cilantro"], 2.4, 12.5, "*s"),
        D("Tiradito", ["salmon", "lima", "chile", "aceite"], 2.6, 13.5, "s"),
        D("Leche de tigre", ["merluza", "lima", "chile", "caldo"], 1.5, 7.5, "s"),
        D("Causa limeña", ["patata", "atun", "mayo", "aguacate"], 1.6, 9.0, ""),
        D("Lomo saltado", ["ternera", "tomate", "cebolla", "soja", "patata"], 2.8, 14.0, ""),
        D("Ají de gallina", ["pollo", "chile", "leche", "pan"], 2.0, 11.0, "s"),
        D("Inca cola", ["soda", "hielo"], 0.3, 2.2, "v"),
        D("Suspiro limeño", ["leche", "azucar", "huevo"], 0.7, 4.5, "v"),
      ],
    },
    {
      id: "farol",
      name: "Sabor Izakaya",
      short: "IF",
      cuisines: ["japonesa", "izakaya"],
      tier: "casual",
      color: "#DC2F02",
      color2: "#6A040F",
      tagline: "El farol rojo se enciende al anochecer.",
      dishes: [
        D("Yakitori", ["pollo", "soja", "azucar"], 1.4, 7.5, "*"),
        D("Karaage", ["pollo", "jengibre", "soja", "aceite"], 1.5, 8.0, ""),
        D("Takoyaki", ["pulpo", "masa", "salsa", "ajonjoli"], 1.4, 7.0, ""),
        D("Agedashi tofu", ["tofu", "caldo", "ajonjoli"], 1.0, 6.0, "v"),
        D("Edamame", ["edamame"], 0.5, 3.5, "v"),
        D("Onigiri", ["arroz", "algas", "atun"], 0.8, 4.2, ""),
        D("Sake caliente", ["licor"], 1.6, 5.5, "a"),
        D("Highball", ["whisky", "soda", "hielo"], 1.8, 6.5, "a"),
      ],
    },
    {
      id: "marea",
      name: "Rama Fish",
      short: "FM",
      cuisines: ["británica", "pescado"],
      tier: "casual",
      color: "#1D3557",
      color2: "#457B9D",
      tagline: "La marea trae el rebozado.",
      dishes: [
        D("Fish and chips", ["bacalao", "patata", "aceite", "limon"], 2.4, 11.5, "*"),
        D("Mushy peas", ["guisantes".replace("guisantes","judias"), "menta"], 0.5, 2.8, "v"),
        D("Pie de carne", ["ternera", "masa", "caldo"], 2.0, 10.5, ""),
        D("Scampi", ["gamba", "aceite", "limon"], 2.2, 12.0, ""),
        D("Butter chicken pie", ["pollo", "masa", "mantequilla"], 1.8, 9.5, ""),
        D("Sticky toffee", ["azucar", "mantequilla", "huevo"], 0.8, 4.8, "v"),
        D("Pinta", ["cerveza"], 0.7, 4.2, "a"),
        D("Té con leche", ["te", "leche"], 0.3, 2.0, "v"),
      ],
    },
    {
      id: "carbon",
      name: "Sabo BBQ",
      short: "BC",
      cuisines: ["americana", "barbacoa"],
      tier: "casual",
      color: "#6F1D1B",
      color2: "#BB9457",
      tagline: "Humo lento, hambre rápida.",
      dishes: [
        D("Brisket", ["ternera", "pimenton", "azucar"], 3.6, 16.5, "*"),
        D("Costillas", ["costilla", "salsa", "azucar"], 2.8, 14.5, ""),
        D("Pulled pork", ["cerdo", "salsa", "pan"], 2.0, 11.0, ""),
        D("Pollo ahumado", ["pollo", "pimenton"], 1.8, 10.5, ""),
        D("Mac and cheese", ["pasta", "cheddar", "leche"], 1.2, 6.5, "v"),
        D("Coleslaw", ["lechuga", "mayo", "vinagre"], 0.5, 3.2, "v"),
        D("Cornbread", ["maiz", "mantequilla", "huevo"], 0.5, 3.0, "v"),
        D("Bourbon copa", ["whisky"], 2.8, 7.5, "a"),
      ],
    },
    {
      id: "alpina",
      name: "Orama Fondue",
      short: "FA",
      cuisines: ["suiza", "alpina"],
      tier: "casual",
      color: "#B08968",
      color2: "#7F4F24",
      tagline: "El queso no entiende de fronteras.",
      dishes: [
        D("Fondue mixte", ["queso_gruyere", "vino_blanco", "pan", "ajo"], 3.2, 16.0, "v*"),
        D("Raclette", ["queso_raclette", "patata", "pepino"], 3.0, 15.5, "v"),
        D("Rösti", ["patata", "mantequilla"], 1.0, 7.5, "v"),
        D("Geschnetzeltes", ["ternera", "nata", "setas", "vino_blanco"], 3.4, 17.0, ""),
        D("Sopa cebolla alpina", ["cebolla", "caldo", "queso"], 1.2, 7.0, "v"),
        D("Tarta nuez", ["almendra", "azucar", "huevo"], 1.0, 5.5, "v"),
        D("Vino fendant", ["vino_blanco"], 1.3, 5.5, "a"),
        D("Chocolate caliente", ["chocolate", "leche"], 0.6, 3.5, "v"),
      ],
    },
    {
      id: "nieve",
      name: "Sabor Pierogi",
      short: "PN",
      cuisines: ["polaca", "del este"],
      tier: "casual",
      color: "#C1121F",
      color2: "#FDF0D5",
      tagline: "Bajo la nieve, el relleno.",
      dishes: [
        D("Pierogi ruskie", ["masa_pierogi", "patata", "queso", "cebolla"], 1.2, 8.5, "v*"),
        D("Pierogi carne", ["masa_pierogi", "carne_picada", "cebolla"], 1.4, 9.0, ""),
        D("Bigos", ["cerdo", "chorizo", "tomate"], 1.8, 10.5, ""),
        D("Żurek", ["caldo", "huevo", "cerdo"], 1.2, 7.5, ""),
        D("Schabowy", ["cerdo", "patata", "huevo"], 2.2, 11.5, ""),
        D("Sopa de remolacha", ["caldo", "nata"], 0.9, 6.0, "v"),
        D("Vodka copa", ["vodka", "hielo"], 1.6, 4.5, "a"),
        D("Sernik", ["queso", "azucar", "huevo"], 0.9, 4.8, "v"),
      ],
    },
    {
      id: "arena",
      name: "Rama Tagine",
      short: "TA",
      cuisines: ["marroquí", "magrebí"],
      tier: "casual",
      color: "#E09F3E",
      color2: "#9C6644",
      tagline: "La arena guarda el fuego.",
      dishes: [
        D("Tagine cordero", ["cordero", "comino", "almendra", "miel"], 3.0, 14.5, "*"),
        D("Pollo limón aceitunas", ["pollo", "limon", "comino", "aceite"], 2.2, 12.0, ""),
        D("Couscous verduras", ["trigo".replace("trigo","arroz"), "zanahoria".replace("zanahoria","tomate"), "garbanzo"], 1.4, 9.5, "v"),
        D("Harira", ["lenteja", "tomate", "cilantro", "comino"], 1.0, 6.5, "v"),
        D("Pastela", ["masa", "pollo", "almendra", "canela"], 2.0, 11.5, ""),
        D("Ensalada zaalouk", ["tomate", "ajo", "comino", "aceite"], 0.8, 5.5, "v"),
        D("Té menta", ["te", "menta", "azucar"], 0.3, 2.2, "v"),
        D("Gazelle", ["almendra", "azucar", "naranja"], 0.7, 3.8, "v"),
      ],
    },
    {
      id: "jerk",
      name: "Sabo Jerk",
      short: "JC",
      cuisines: ["caribeña"],
      tier: "casual",
      color: "#008000",
      color2: "#FFD100",
      tagline: "El coco y el humo se conocen en la playa.",
      dishes: [
        D("Jerk chicken", ["pollo", "jerk", "lima"], 1.8, 11.0, "*s"),
        D("Jerk pork", ["cerdo", "jerk"], 2.0, 11.5, "s"),
        D("Rice and peas", ["arroz", "coco", "judias"], 0.8, 5.0, "v"),
        D("Festival", ["masa", "azucar", "aceite"], 0.5, 3.2, "v"),
        D("Ackee saltfish", ["bacalao", "tomate", "pimiento"], 2.2, 12.0, ""),
        D("Plátano frito", ["platano_macho", "aceite"], 0.4, 3.0, "v"),
        D("Rum punch", ["ron", "pina", "naranja", "lima"], 1.6, 6.5, "a"),
        D("Coco fresco", ["coco", "hielo"], 0.5, 3.0, "v"),
      ],
    },
    {
      id: "dumpling",
      name: "Orama Dumpling",
      short: "DT",
      cuisines: ["china", "dim sum"],
      tier: "casual",
      color: "#9B5DE5",
      color2: "#F15BB5",
      tagline: "El té abre, el dumpling cierra.",
      dishes: [
        D("Xiaolongbao", ["masa", "cerdo", "caldo", "jengibre"], 1.6, 8.5, "*"),
        D("Har gow", ["masa", "gamba", "jengibre"], 1.8, 9.0, ""),
        D("Siu mai", ["masa", "cerdo", "gamba"], 1.5, 8.0, ""),
        D("Cheung fun", ["arroz", "soja", "ajonjoli"], 1.1, 6.5, "v"),
        D("Huevo custard bao", ["bao", "huevo", "azucar"], 0.8, 4.5, "v"),
        D("Costilla vapor", ["costilla", "soja", "pimiento"], 1.8, 8.8, ""),
        D("Té pu-erh", ["te"], 0.3, 2.0, "v"),
        D("Té jazmín pot", ["te"], 0.3, 2.2, "v"),
      ],
    },
    {
      id: "poke",
      name: "Sabor Poké",
      short: "PV",
      cuisines: ["hawaiana", "poké"],
      tier: "casual",
      color: "#FF6B35",
      color2: "#004E89",
      tagline: "El volcán se come crudo y frío.",
      dishes: [
        D("Poké atún", ["atun", "arroz", "soja", "aguacate", "ajonjoli"], 2.6, 12.5, "*"),
        D("Poké salmón", ["salmon", "arroz", "lima", "cebolla"], 2.4, 12.0, ""),
        D("Poké tofu", ["tofu", "arroz", "aguacate", "edamame"], 1.6, 10.0, "v"),
        D("Açaí bowl", ["platano", "fruta".replace("fruta","mango"), "coco"], 1.2, 7.5, "v"),
        D("Spam musubi", ["arroz", "cerdo", "algas"], 1.1, 5.5, ""),
        D("Edamame chile", ["edamame", "chile", "sal".replace("sal","lima")], 0.6, 3.8, "vs"),
        D("Agua de hibisco", ["agua", "lima", "azucar"], 0.2, 2.2, "v"),
        D("Piña grill", ["pina", "azucar"], 0.5, 3.5, "v"),
      ],
    },
    {
      id: "etoile",
      name: "Rama Étoile",
      short: "MÉ",
      cuisines: ["francesa", "alta cocina"],
      tier: "luxury",
      color: "#1B1B1B",
      color2: "#C9A227",
      tagline: "Una estrella por cubierto.",
      dishes: [
        D("Menú dégustation", ["foie", "trufa", "ternera", "vino_tinto"], 18, 85, "*"),
        D("Foie mi-cuit", ["foie", "pan", "vino_tinto"], 8, 28, ""),
        D("Saint-Jacques", ["vieira", "mantequilla", "limon"], 6, 32, ""),
        D("Pigeon trufado", ["pavo", "trufa", "vino_tinto"], 9, 38, ""),
        D("Soufflé queso", ["huevo", "queso_gruyere", "nata"], 3.5, 18, "v"),
        D("Tarte tatin", ["azucar", "mantequilla", "masa"], 2.0, 12, "v"),
        D("Grand cru copa", ["vino_tinto"], 6, 18, "a"),
        D("Champagne coupe", ["cava"], 3.5, 16, "a"),
      ],
    },
    {
      id: "sakura",
      name: "Sabo Sakura",
      short: "SI",
      cuisines: ["japonesa", "kaiseki"],
      tier: "luxury",
      color: "#FFB7C5",
      color2: "#5C2A3A",
      tagline: "El cerezo no se apresura.",
      dishes: [
        D("Omakase", ["atun", "salmon", "caviar", "wasabi", "arroz_sushi"], 22, 95, "*"),
        D("Sashimi imperial", ["atun", "salmon", "wasabi"], 8, 36, ""),
        D("Chawanmushi", ["huevo", "caldo", "gamba"], 3, 16, ""),
        D("Wagyu teppan", ["wagyu", "soja", "ajonjoli"], 16, 68, ""),
        D("Tempura kaiseki", ["gamba", "aceite", "harina".replace("harina","masa")], 5, 24, ""),
        D("Mochi matcha", ["te", "azucar", "arroz"], 1.2, 9, "v"),
        D("Sake daiginjō", ["licor"], 4, 14, "a"),
        D("Té ceremonial", ["te"], 0.8, 8, "v"),
      ],
    },
    {
      id: "palazzo",
      name: "Orama Palazzo",
      short: "PO",
      cuisines: ["italiana", "alta cocina"],
      tier: "luxury",
      color: "#C9A227",
      color2: "#3D1F00",
      tagline: "El palacio se sirve en plato blanco.",
      dishes: [
        D("Tajarin trufa blanca", ["pasta", "trufa_blanca", "mantequilla", "parmesano"], 14, 48, "v*"),
        D("Risotto azafrán", ["arroz", "azafran", "parmesano", "mantequilla"], 4.5, 26, "v"),
        D("Branzino al sale", ["merluza", "limon", "aceite", "romero"], 6, 34, ""),
        D("Vitello tonnato", ["ternera", "atun", "mayo", "alcaparras".replace("alcaparras","limon")], 4.2, 22, ""),
        D("Burrata oro", ["mozzarella", "tomate", "aceite", "albahaca"], 3.5, 18, "v"),
        D("Panna cotta", ["nata", "vainilla", "azucar"], 1.4, 10, "v"),
        D("Barolo copa", ["vino_tinto"], 5, 16, "a"),
        D("Espresso oro", ["cafe"], 0.4, 3.5, "v"),
      ],
    },
    {
      id: "nord",
      name: "Sabor Nord",
      short: "NH",
      cuisines: ["nórdica"],
      tier: "luxury",
      color: "#CAD2C5",
      color2: "#2F3E46",
      tagline: "El hielo también se cocina.",
      dishes: [
        D("Menú boreal", ["salmon", "menta", "patata", "miel"], 16, 78, "*"),
        D("Salmón curado", ["salmon", "eneldo".replace("eneldo","menta"), "azucar"], 4, 22, ""),
        D("Vieira nieve", ["vieira", "aceite", "limon"], 5.5, 28, ""),
        D("Ciervo (o ternera) bosque", ["ternera", "setas", "bayas".replace("bayas","arandanos")], 7, 36, ""),
        D("Pan de centeno", ["pan", "mantequilla"], 0.8, 6, "v"),
        D("Skyr miel", ["yogurt", "miel"], 1.0, 9, "v"),
        D("Aquavit", ["licor", "hielo"], 2.2, 9, "a"),
        D("Cerveza de granja", ["cerveza"], 0.9, 7, "a"),
      ],
    },
    {
      id: "rubi",
      name: "Rama Mediterráneo",
      short: "TRB",
      cuisines: ["mediterránea", "alta cocina"],
      tier: "luxury",
      color: "#9B2226",
      color2: "#BB3E03",
      tagline: "El Mediterráneo, en terraza.",
      dishes: [
        D("Menú meridia", ["aceite", "tomate", "pescado".replace("pescado","merluza"), "citrus".replace("citrus","limon")], 14, 72, "*"),
        D("Tartar tomate", ["tomate", "aceite", "albahaca"], 2.5, 16, "v"),
        D("Lubina sal", ["merluza", "aceite", "limon"], 5.5, 32, ""),
        D("Cordero romero", ["cordero", "romero", "ajo"], 6.5, 34, ""),
        D("Burrata cítricos", ["mozzarella", "naranja", "aceite"], 3.2, 18, "v"),
        D("Helado AOVE", ["aceite", "azucar", "leche"], 1.4, 10, "v"),
        D("Priorat copa", ["vino_tinto"], 4.5, 14, "a"),
        D("Vermú reserva", ["vermut", "naranja", "hielo"], 1.4, 7, "a"),
      ],
    },
    {
      id: "mar",
      name: "Sabo Mar",
      short: "CDM",
      cuisines: ["mariscos", "alta cocina"],
      tier: "luxury",
      color: "#023E8A",
      color2: "#48CAE4",
      tagline: "El mar se sienta a la mesa.",
      dishes: [
        D("Mariscada corte", ["langosta", "ostra", "gamba", "percebe", "limon"], 22, 88, "*"),
        D("Ostras 6", ["ostra", "limon"], 8, 28, ""),
        D("Langosta mantequilla", ["langosta", "mantequilla", "limon"], 14, 62, ""),
        D("Percebes", ["percebe", "limon"], 9, 36, ""),
        D("Arroz señoret", ["arroz", "gamba", "azafran", "caldo"], 5, 28, ""),
        D("Tarta limón", ["limon", "huevo", "azucar", "masa"], 1.4, 10, "v"),
        D("Albariño", ["vino_blanco"], 2.2, 8, "a"),
        D("Champagne brut", ["cava"], 3.5, 16, "a"),
      ],
    },
    {
      id: "seda",
      name: "Orama Seda",
      short: "MS",
      cuisines: ["china", "cantonesa"],
      tier: "luxury",
      color: "#9D0208",
      color2: "#E9C46A",
      tagline: "La seda no se ve, se saborea.",
      dishes: [
        D("Pato laqueado seda", ["pavo", "pepino", "salsa", "tortilla"], 8, 42, "*"),
        D("Dim sum imperial", ["gamba", "cerdo", "masa"], 6, 32, ""),
        D("Abalón (o vieira) soja", ["vieira", "soja", "ajonjoli"], 7, 38, ""),
        D("Pescado vapor jengibre", ["merluza", "jengibre", "soja"], 5, 28, ""),
        D("Verduras jade", ["judias", "ajo", "aceite"], 2, 14, "v"),
        D("Sopa nido (caldo)", ["caldo", "setas"], 3, 16, "v"),
        D("Baijiu copa", ["licor"], 2.4, 10, "a"),
        D("Té tieguanyin", ["te"], 0.6, 6, "v"),
      ],
    },
    {
      id: "roble",
      name: "Sabor Asador",
      short: "AR",
      cuisines: ["asador", "carnes"],
      tier: "luxury",
      color: "#3D2914",
      color2: "#8B5E34",
      tagline: "La vaca, el fuego y el roble.",
      dishes: [
        D("Chuletón 1 kg", ["ternera", "sal".replace("sal","pimenton"), "romero"], 14, 62, "*"),
        D("Solomillo", ["ternera", "pimienta".replace("pimienta","pimenton")], 9, 38, ""),
        D("Ibérico pluma", ["ibérico", "aceite"], 8, 34, ""),
        D("Kobe bocado", ["kobe", "sal".replace("sal","aceite")], 16, 75, ""),
        D("Pencas y pimientos", ["pimiento", "aceite"], 1.4, 8, "v"),
        D("Tarta queso fuego", ["queso", "azucar", "huevo"], 1.6, 9, "v"),
        D("Ribera copa", ["vino_tinto"], 3.5, 9, "a"),
        D("Brandy solera", ["brandy"], 2.4, 8, "a"),
      ],
    },
    {
      id: "latitud",
      name: "Rama Cóctel",
      short: "CL",
      cuisines: ["cócteles"],
      tier: "bar",
      color: "#7209B7",
      color2: "#3A0CA3",
      tagline: "Cada copa, un meridiano.",
      dishes: [
        D("Negroni latitud", ["ginebra", "vermut", "licor", "hielo"], 2.4, 9.5, "a*"),
        D("Old fashioned", ["whisky", "azucar", "hielo"], 2.8, 10.5, "a"),
        D("Daiquiri", ["ron", "lima", "azucar"], 1.8, 8.5, "a"),
        D("Martini", ["ginebra", "vermut", "hielo"], 2.2, 9.5, "a"),
        D("Spritz", ["licor", "cava", "naranja", "hielo"], 1.8, 7.5, "a"),
        D("Mocktail brújula", ["lima", "menta", "soda", "azucar"], 0.5, 4.5, "v"),
        D("Aceitunas y almendras", ["almendra", "aceite"], 0.8, 4.0, "v"),
        D("Steak tartar mini", ["ternera", "huevo", "mostaza"], 2.4, 9.0, ""),
      ],
    },
    {
      id: "bodega",
      name: "Sabo Bodega",
      short: "BME",
      cuisines: ["vinos"],
      tier: "bar",
      color: "#6A040F",
      color2: "#9D0208",
      tagline: "La bodega del holding, abierta al mundo.",
      dishes: [
        D("Cata 3 tintos", ["vino_tinto"], 4.2, 14, "a*"),
        D("Copa reserva", ["vino_tinto"], 2.2, 6.5, "a"),
        D("Copa blanco", ["vino_blanco"], 1.8, 5.5, "a"),
        D("Tabla ibéricos", ["ibérico", "pan", "tomate"], 4.5, 16, ""),
        D("Quesos del mundo", ["queso", "miel", "pan"], 3.2, 13, "v"),
        D("Anchoas y mantequilla", ["anchoa", "mantequilla", "pan"], 1.8, 8, ""),
        D("Vermú grifo", ["vermut", "naranja", "hielo"], 1.2, 3.8, "a"),
        D("Agua con gas", ["agua", "hielo", "limon"], 0.1, 1.8, "v"),
      ],
    },
    {
      id: "cerveza",
      name: "Orama Cerveza",
      short: "CB",
      cuisines: ["cerveza", "pub"],
      tier: "bar",
      color: "#F77F00",
      color2: "#FCBF49",
      tagline: "La brújula apunta al grifo.",
      dishes: [
        D("Pinta lager", ["cerveza"], 0.7, 3.8, "a*"),
        D("Pinta IPA", ["cerveza"], 0.8, 4.4, "a"),
        D("Pinta stout", ["cerveza"], 0.8, 4.4, "a"),
        D("Tabla 4 tasters", ["cerveza"], 1.6, 7.5, "a"),
        D("Nachos pub", ["maiz", "queso", "chile"], 1.1, 5.5, "v"),
        D("Alitas", ["pollo", "salsa"], 1.4, 6.5, "s"),
        D("Hamburguesa pub", ["pan_burger", "carne_picada", "cheddar"], 1.8, 8.5, ""),
        D("Sidra", ["licor", "hielo"], 1.0, 4.0, "a"),
      ],
    },
    {
      id: "whisky",
      name: "Sabor Whisky",
      short: "WS",
      cuisines: ["whisky"],
      tier: "bar",
      color: "#583101",
      color2: "#BB9457",
      tagline: "Sesenta maltes, un solo meridiano.",
      dishes: [
        D("Single malt 12", ["whisky"], 3.2, 11, "a*"),
        D("Blend de la casa", ["whisky"], 2.2, 7.5, "a"),
        D("Highball 60", ["whisky", "soda", "hielo"], 2.0, 8.0, "a"),
        D("Old pal", ["whisky", "vermut"], 2.6, 9.5, "a"),
        D("Tabla ahumados", ["salmon", "pan", "mantequilla"], 2.8, 12, ""),
        D("Chocolate 70%", ["chocolate"], 0.9, 5, "v"),
        D("Puro de chocolate", ["chocolate", "cacao".replace("cacao","chocolate")], 0.8, 4.5, "v"),
        D("Agua mineral", ["agua"], 0.1, 2.2, "v"),
      ],
    },
    {
      id: "eclipse",
      name: "Rama Café",
      short: "CE",
      cuisines: ["café", "licores"],
      tier: "bar",
      color: "#212529",
      color2: "#6C757D",
      tagline: "Cuando el café se encuentra con la noche.",
      dishes: [
        D("Espresso", ["cafe"], 0.3, 1.6, "v*"),
        D("Flat white", ["cafe", "leche"], 0.45, 2.8, "v"),
        D("Irish coffee", ["cafe", "whisky", "nata", "azucar"], 1.8, 6.5, "a"),
        D("Carajillo", ["cafe", "brandy"], 1.4, 4.5, "a"),
        D("Croissant mantequilla", ["croissant", "mantequilla"], 0.5, 2.6, "v"),
        D("Tarta eclipse", ["chocolate", "cafe", "nata"], 1.0, 4.8, "v"),
        D("Licor de café", ["licor", "cafe"], 1.5, 5.0, "a"),
        D("Infusion", ["te"], 0.3, 2.2, "v"),
      ],
    },
    {
      id: "tequila",
      name: "Sabo Tequila",
      short: "TS",
      cuisines: ["tequila", "mezcal"],
      tier: "bar",
      color: "#2A9D8F",
      color2: "#E9C46A",
      tagline: "El sol se bebe con sal y lima.",
      dishes: [
        D("Margarita sol", ["tequila", "lima", "licor", "hielo"], 2.0, 8.5, "a*"),
        D("Paloma", ["tequila", "soda", "lima", "hielo"], 1.8, 7.5, "a"),
        D("Mezcal copa", ["mezcal"], 2.6, 9.0, "a"),
        D("Tequila reposado", ["tequila"], 2.2, 7.5, "a"),
        D("Elote", ["maiz", "mayo", "chile", "lima"], 0.7, 4.2, "vs"),
        D("Guacamole", ["aguacate", "lima", "tomate"], 0.9, 5.0, "v"),
        D("Taco de bar", ["tortilla", "cerdo", "cilantro"], 1.1, 3.8, ""),
        D("Agua jamaica", ["agua", "lima", "azucar"], 0.2, 2.2, "v"),
      ],
    },
    {
      id: "polar",
      name: "Orama Champagne",
      short: "CHP",
      cuisines: ["champán"],
      tier: "bar",
      color: "#F8F1E3",
      color2: "#C9A227",
      tagline: "Burbujas para el paralelo 90.",
      dishes: [
        D("Coupe brut", ["cava"], 3.5, 12, "a*"),
        D("Rosé polar", ["cava"], 3.8, 14, "a"),
        D("Kir royal", ["cava", "licor"], 3.6, 13, "a"),
        D("Bellini", ["cava", "mango"], 3.2, 11, "a"),
        D("Ostras 3", ["ostra", "limon"], 4.5, 16, ""),
        D("Caviar blini", ["caviar", "nata", "pan"], 10, 32, ""),
        D("Macaron", ["almendra", "azucar", "huevo"], 0.8, 4.5, "v"),
        D("Agua de glaciar", ["agua"], 0.1, 3.5, "v"),
      ],
    },
    {
      id: "tropico",
      name: "Sabor Ron",
      short: "RT",
      cuisines: ["ron", "tiki"],
      tier: "bar",
      color: "#E85D04",
      color2: "#2A9D8F",
      tagline: "El trópico cabe en un tiki.",
      dishes: [
        D("Mai tai", ["ron", "lima", "licor", "hielo"], 2.2, 9.0, "a*"),
        D("Piña colada", ["ron", "pina", "coco", "hielo"], 2.0, 8.5, "a"),
        D("Dark 'n' stormy", ["ron", "lima", "hielo"], 1.8, 8.0, "a"),
        D("Zombie", ["ron", "naranja", "lima", "licor"], 2.8, 11.0, "a"),
        D("Alitas tiki", ["pollo", "pina", "chile"], 1.5, 6.5, "s"),
        D("Brocheta pina", ["pina", "azucar"], 0.5, 3.5, "v"),
        D("Coco agua", ["coco", "hielo"], 0.5, 3.0, "v"),
        D("Cerveza tropic", ["cerveza"], 0.7, 3.8, "a"),
      ],
    },
    {
      id: "vermu",
      name: "Rama Vermú",
      short: "VP",
      cuisines: ["vermutería"],
      tier: "bar",
      color: "#AE2012",
      color2: "#0A9396",
      tagline: "La plaza, el hielo y la hora del vermú.",
      dishes: [
        D("Vermú rojo grifo", ["vermut", "naranja", "hielo"], 1.2, 3.2, "a*"),
        D("Vermú blanco", ["vermut", "limon", "hielo"], 1.2, 3.2, "a"),
        D("Spritz plaza", ["vermut", "cava", "hielo"], 1.6, 4.8, "a"),
        D("Gilda", ["anchoa", "pimiento"], 0.8, 2.8, ""),
        D("Patatas bravas", ["patata", "salsa", "pimenton"], 0.6, 3.5, "vs"),
        D("Aceitunas", ["aceite"], 0.3, 1.8, "v"),
        D("Banderilla", ["anchoa", "pepino"], 0.6, 2.4, ""),
        D("Tinto verano", ["vino_tinto", "soda", "limon"], 1.0, 3.0, "a"),
      ],
    },
    {
      id: "absenta",
      name: "Sabo Absenta",
      short: "AL",
      cuisines: ["absenta", "cócteles"],
      tier: "bar",
      color: "#2D6A4F",
      color2: "#081C15",
      tagline: "La luna verde, con cuchara.",
      dishes: [
        D("Absenta ritual", ["absenta", "azucar", "agua"], 3.2, 10, "a*"),
        D("Death in the afternoon", ["absenta", "cava"], 3.6, 12, "a"),
        D("Sazerac", ["whisky", "absenta", "azucar"], 3.0, 11, "a"),
        D("Corpse reviver", ["ginebra", "licor", "absenta", "limon"], 2.8, 10.5, "a"),
        D("Queso azul pan", ["queso", "pan", "miel"], 1.6, 7, "v"),
        D("Chocolate negro", ["chocolate"], 0.9, 4.5, "v"),
        D("Agua ritual", ["agua"], 0.05, 1.5, "v"),
        D("Café verde", ["cafe", "absenta"], 1.6, 6.5, "a"),
      ],
    },
  ];

  /* Arreglar ingredientes inválidos que hayan quedado por reemplazos torpes */
  const VALID = new Set(Object.keys(ING));
  const FALLBACK_ING = "aceite";
  for (const b of BRANDS) {
    b.holding = "Horizon Restaurant Group";
    b.logoFile = "img/filiales/" + b.id + ".png";
    b.logo = `<img src="${b.logoFile}" alt="${b.name}" width="64" height="64">`;
    b.tierInfo = TIERS[b.tier];
    for (const d of b.dishes) {
      d.ings = d.ings.map((x) => (VALID.has(x) ? x : FALLBACK_ING));
      d.id = U.hash32(b.id + d.name).toString(36);
    }
  }

  const BY_ID = Object.fromEntries(BRANDS.map((b) => [b.id, b]));
  const CUISINES = [...new Set(BRANDS.flatMap((b) => b.cuisines))].sort((a, b) => a.localeCompare(b, "es"));

  function brand(id) {
    return BY_ID[id];
  }

  global.BRANDS = BRANDS;
  global.BRAND = {
    list: BRANDS,
    byId: BY_ID,
    tiers: TIERS,
    ings: ING,
    cuisines: CUISINES,
    get: brand,
    logoSVG,
    HOLDING: "Horizon Restaurant Group",
    D,
    normalizeMenus,
  };

  function normalizeMenus() {
    const valid = new Set(Object.keys(ING));
    for (const b of BRANDS) {
      const seen = new Set();
      b.dishes = b.dishes.filter((d) => {
        if (seen.has(d.name)) return false;
        seen.add(d.name);
        return true;
      });
      for (const d of b.dishes) {
        d.ings = (d.ings || []).map((x) => (valid.has(x) ? x : "aceite"));
        d.id = U.hash32(b.id + d.name).toString(36);
      }
    }
  }
})(window);
