/** ISO 3166-1 alpha-2 from ProMods pais_id / nombre */
export const PAIS_ISO = {
  denmark: "DK",
  uk: "GB",
  netherlands: "NL",
  norway: "NO",
  germany: "DE",
  switzerland: "CH",
  poland: "PL",
  slovakia: "SK",
  czech: "CZ",
  belgium: "BE",
  hungary: "HU",
  france: "FR",
  sweden: "SE",
  austria: "AT",
  luxembourg: "LU",
  italy: "IT",
  cyprus: "CY",
  moldova: "MD",
  georgia: "GE",
  spain: "ES",
  albania: "AL",
  aland: "AX",
  slovenia: "SI",
  ukraine: "UA",
  bosnia: "BA",
  finland: "FI",
  croatia: "HR",
  iceland: "IS",
  israel: "IL",
  jordan: "JO",
  russia: "RU",
  belarus: "BY",
  romania: "RO",
  bulgaria: "BG",
  serbia: "RS",
  turkey: "TR",
  lithuania: "LT",
  latvia: "LV",
  estonia: "EE",
  ireland: "IE",
  portugal: "PT",
  greece: "GR",
  macedonia: "MK",
  kosovo: "XK",
  montenegro: "ME",
  armenia: "AM",
  azerbaijan: "AZ",
  morocco: "MA",
  tunisia: "TN",
  egypt: "EG",
  kazakhstan: "KZ",
  lebanon: "LB",
  syria: "SY",
  saudi: "SA",
  saudia: "SA",
  iraq: "IQ",
  malta: "MT",
  andorra: "AD",
  monaco: "MC",
  greenland: "GL",
  svalbard: "SJ",
  westbank: "PS",
  "faroe islands": "FO",
  faroe: "FO",
  gibraltar: "GI",
  liechtenstein: "LI",
  liecht: "LI",
  "northern ireland": "GB",
  northern_ireland: "GB",
  nireland: "GB",
  guernsey: "GG",
  jersey: "JE",
  iom: "IM",
};

export function isoOf(stop) {
  if (!stop) return "XX";
  const id = String(stop.pais_id || "").toLowerCase();
  if (PAIS_ISO[id]) return PAIS_ISO[id];
  // fallback by Spanish name
  const map = {
    Dinamarca: "DK",
    "Reino Unido": "GB",
    "Países Bajos": "NL",
    Noruega: "NO",
    Alemania: "DE",
    Suiza: "CH",
    Polonia: "PL",
    Eslovaquia: "SK",
    Chequia: "CZ",
    Bélgica: "BE",
    Hungría: "HU",
    Francia: "FR",
    Suecia: "SE",
    Austria: "AT",
    Luxemburgo: "LU",
    Italia: "IT",
    España: "ES",
    Rusia: "RU",
    Bielorrusia: "BY",
    Ucrania: "UA",
    Rumanía: "RO",
    Turquía: "TR",
    Portugal: "PT",
    Grecia: "GR",
    Serbia: "RS",
    Bulgaria: "BG",
    Croacia: "HR",
    "Bosnia y Herzegovina": "BA",
    Albania: "AL",
    "Macedonia del Norte": "MK",
    Montenegro: "ME",
    Kosovo: "XK",
    Eslovenia: "SI",
    Moldavia: "MD",
    Georgia: "GE",
    Armenia: "AM",
    Azerbaiyán: "AZ",
    Israel: "IL",
    Jordania: "JO",
    Líbano: "LB",
    Siria: "SY",
    Egipto: "EG",
    Marruecos: "MA",
    Túnez: "TN",
    "Arabia Saudí": "SA",
    Irak: "IQ",
    Kazajistán: "KZ",
    Chipre: "CY",
    Islandia: "IS",
    Estonia: "EE",
    Letonia: "LV",
    Lituania: "LT",
    Finlandia: "FI",
    Irlanda: "IE",
    "Irlanda del Norte": "GB",
    Malta: "MT",
    Andorra: "AD",
    Mónaco: "MC",
    Liechtenstein: "LI",
    Gibraltar: "GI",
    Groenlandia: "GL",
    Svalbard: "SJ",
    Cisjordania: "PS",
    "Islas Feroe": "FO",
    "Isla de Man": "IM",
    Guernsey: "GG",
    Jersey: "JE",
    Åland: "AX",
  };
  return map[stop.pais] || "XX";
}
