/* Industry Manager v6 — campaña profunda, índices, consejo, audio */
window.IM_CONFIG = {
  name: 'Industry Manager',
  version: '6.0.0',
  realMsPerGameMinute: 1000,
  speeds: [0, 1, 2, 5, 10, 30],
  startingMoney: 100000000,
  saveKey: 'industry_manager_save_v6',
  autosaveMinutesReal: 2,
  inflationYearly: 0.02,
  baseInterestRate: 0.055,
  corporateTax: 0.22,
  maxQuality: 100,
  employeeBaseWageHourly: 18,
  mapDefaultZoom: 5,
  mapCenter: [40.4, -3.7],
  cheatUnlockAllCode: 'INDUSTRIA_TOTAL',
  foundingOfficeCost: 250000,
  exploreCost: 15000,
  energyPriceFloor: 0.05,
  waterPriceFloor: 0.8,
  qualityRejectBelow: 35,
  qualityPremiumAbove: 75,
  campaignOnly: true,
  maintenanceWearPerHour: 0.002,
  seasonCycleDays: 90,
};
