/* Industry Manager — configuración v2 */
window.IM_CONFIG = {
  name: 'Industry Manager',
  version: '2.0.0',
  realMsPerGameMinute: 1000,
  speeds: [0, 1, 2, 5, 10, 30],
  startingMoney: 100000000,
  startingLocation: 'madrid',
  saveKey: 'industry_manager_save_v2',
  autosaveMinutesReal: 2,
  inflationYearly: 0.02,
  baseInterestRate: 0.055,
  corporateTax: 0.22,
  maxQuality: 100,
  employeeBaseWageHourly: 18,
  mapDefaultZoom: 3,
  mapCenter: [30, 10],
  cheatUnlockAllCode: 'INDUSTRIA_TOTAL',
  foundingOfficeCost: 250000,
  energyPriceFloor: 0.05,
  waterPriceFloor: 0.8,
  qualityRejectBelow: 35,
  qualityPremiumAbove: 75,
};
